# Generated by Django 5.2.18 on 2026-10-06 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, verbose_name="نام")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=60, unique=True, verbose_name="نشانی"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="آیکن (bootstrap-icons)"
                    ),
                ),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=120,
                        verbose_name="عنوان (مثلاً نماد اعتماد الکترونیکی)",
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        blank=True, upload_to="uploads/", verbose_name="تصویر نماد"
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="لینک نماد"
                    ),
                ),
                (
                    "embed_code",
                    models.TextField(
                        blank=True,
                        verbose_name="یا کد HTML نماد (اولویت با این است؛ مناسب کد اینماد)",
                    ),
                ),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
        ),
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mobile", models.CharField(db_index=True, max_length=11)),
                ("code_hash", models.CharField(max_length=128)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="عنوان")),
                (
                    "slug",
                    models.CharField(
                        blank=True, max_length=80, unique=True, verbose_name="نشانی"
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, verbose_name="محتوا (HTML مجاز است)"),
                ),
                (
                    "show_in_footer",
                    models.BooleanField(
                        default=True, verbose_name="نمایش لینک در فوتر"
                    ),
                ),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
        ),
        migrations.CreateModel(
            name="SiteSetting",
            fields=[
                (
                    "key",
                    models.CharField(max_length=80, primary_key=True, serialize=False),
                ),
                ("value", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=120, verbose_name="عنوان"),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.FileField(
                        upload_to="uploads/", verbose_name="تصویر (پیشنهادی ۱۶۰۰×۶۰۰)"
                    ),
                ),
                (
                    "link",
                    models.CharField(blank=True, max_length=255, verbose_name="لینک"),
                ),
                ("sort", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
        ),
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, verbose_name="نام مجموعه / سالن"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=60, verbose_name="شهر"),
                ),
                (
                    "address",
                    models.CharField(blank=True, max_length=255, verbose_name="آدرس"),
                ),
                (
                    "map_url",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="لینک نقشه"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(max_length=11, unique=True, verbose_name="موبایل"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=80, verbose_name="نام"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("customer", "کاربر"), ("admin", "مدیر")],
                        default="customer",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=150, unique=True)),
                ("subtitle", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("poster", models.FileField(blank=True, upload_to="uploads/")),
                ("venue_name", models.CharField(blank=True, max_length=200)),
                ("venue_address", models.CharField(blank=True, max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="draft", max_length=20)),
                ("sales_open", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticketing.category",
                    ),
                ),
                (
                    "hall",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticketing.hall",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("sales_open", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="ticketing.event",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
            },
        ),
        migrations.CreateModel(
            name="HallLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("sort", models.PositiveIntegerField(default=0)),
                ("width", models.PositiveIntegerField(default=1200)),
                ("height", models.PositiveIntegerField(default=800)),
                ("shapes", models.JSONField(blank=True, default=list)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="ticketing.hall",
                    ),
                ),
            ],
            options={
                "ordering": ["sort", "id"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                (
                    "status",
                    models.CharField(db_index=True, default="pending", max_length=20),
                ),
                ("total", models.PositiveBigIntegerField(default=0)),
                ("gateway", models.CharField(blank=True, max_length=30)),
                ("expires_at", models.DateTimeField(null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="ticketing.event",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="ticketing.eventsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(max_length=30)),
                ("amount", models.PositiveBigIntegerField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("authority", models.CharField(blank=True, max_length=255, null=True)),
                ("ref_id", models.CharField(blank=True, max_length=100, null=True)),
                ("card_pan", models.CharField(blank=True, max_length=40, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("raw", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="ticketing.order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeatCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("color", models.CharField(default="#6c5ce7", max_length=9)),
                (
                    "hall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="ticketing.hall",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_label", models.CharField(blank=True, max_length=20, null=True)),
                ("label", models.CharField(max_length=30)),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                (
                    "level",
                    models.ForeignKey(
                        db_column="hall_level_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="ticketing.halllevel",
                    ),
                ),
                (
                    "seat_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticketing.seatcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("price", models.PositiveBigIntegerField(default=0)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="ticketing.event",
                    ),
                ),
                (
                    "seat_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticketing.seatcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                (
                    "ticket_code",
                    models.CharField(blank=True, max_length=16, null=True, unique=True),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "lock_key",
                    models.CharField(blank=True, max_length=40, null=True, unique=True),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ticketing.event",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="ticketing.order",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ticketing.eventsession",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ticketing.seat",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="ticketing.tickettype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="hall",
            name="venue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="halls",
                to="ticketing.venue",
            ),
        ),
        migrations.CreateModel(
            name="SeatPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seat_prices",
                        to="ticketing.event",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="ticketing.seat",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "seat")},
            },
        ),
    ]
